import type Database from 'better-sqlite3'
import { createHash } from 'node:crypto'
import { copyFile,writeFile } from 'node:fs/promises'
import { basename,join } from 'node:path'
import { dialog,ipcMain } from 'electron'
import { z } from 'zod'
import { inspectBase64 } from '../response/base64-inspector'
import type { ResponseResourceRegistry } from '../response/response-resource-registry'
const id=z.string().uuid(),fail=(message:string)=>({ok:false,error:{code:'INVALID_RESOURCE',category:'resource',message,retryable:false}})
const safeName=(value:string)=>{let name=[...basename(value)].map(c=>c.charCodeAt(0)<32||'<>:"/\\|?*'.includes(c)?'_':c).join('').replace(/[. ]+$/,'').slice(0,120)||'response.bin';if(/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(\.|$)/i.test(name))name=`_${name}`;return name}
const extension=(mime:string|null)=>({'image/png':'.png','image/jpeg':'.jpg','image/webp':'.webp','audio/wav':'.wav','audio/mpeg':'.mp3','video/mp4':'.mp4','application/pdf':'.pdf'}[mime||'']||'.bin')
export function registerResponseResourceHandlers(db:Database.Database,registry:ResponseResourceRegistry,assetRoot:string){
 ipcMain.handle('response-resources:descriptor',(_e,input)=>{const p=z.object({resourceId:id}).strict().safeParse(input);try{return p.success?{ok:true,data:registry.get(p.data.resourceId)}:fail('Invalid resource.')}catch{return fail('Resource is not available.')}})
 ipcMain.handle('response-resources:preview',async(_e,input)=>{const p=z.object({resourceId:id,offset:z.number().int().min(0).default(0),length:z.number().int().min(1).max(16384).default(4096)}).strict().safeParse(input);try{return p.success?{ok:true,data:await registry.readPreview(p.data.resourceId,p.data.offset,p.data.length)}:fail('Invalid preview request.')}catch{return fail('Resource preview is not available.')}})
 ipcMain.handle('response-resources:inspect-base64',(_e,input)=>{const p=z.object({value:z.string().max(70*1024*1024)}).strict().safeParse(input);try{if(!p.success)return fail('Base64 input is too large.');const inspected=inspectBase64(p.data.value),data={declaredMimeType:inspected.declaredMimeType,byteLength:inspected.byteLength,classification:inspected.classification};return {ok:true,data}}catch(error){return fail(error instanceof Error?error.message:'Base64 inspection failed.')}})
 ipcMain.handle('response-resources:extract-base64',async(_e,input)=>{const p=z.object({historyId:id,jsonPath:z.string().min(1).max(1000),value:z.string().max(70*1024*1024)}).strict().safeParse(input);try{if(!p.success)return fail('Invalid Base64 extraction.');if(!db.prepare('SELECT 1 FROM request_history WHERE id=?').get(p.data.historyId))return fail('History is not available.');const inspected=inspectBase64(p.data.value),digest=createHash('sha256').update(inspected.bytes).digest('hex'),existing=db.prepare("SELECT id FROM response_resources WHERE history_id=? AND source='base64-extraction' AND digest=?").get(p.data.historyId,digest) as {id:string}|undefined;if(existing)return {ok:true,data:registry.get(existing.id)};const history=db.prepare('SELECT workspace_id FROM request_history WHERE id=?').get(p.data.historyId) as {workspace_id:string},dir=join(assetRoot,history.workspace_id,p.data.historyId),path=join(dir,`extraction-${digest}.bin`);await import('node:fs/promises').then(v=>v.mkdir(dir,{recursive:true}));await writeFile(path,inspected.bytes);const c=inspected.classification,name=`extraction-${digest.slice(0,8)}${extension(c.effectiveMimeType)}`;return {ok:true,data:await registry.register({historyId:p.data.historyId,source:'base64-extraction',kind:c.kind==='image'||c.kind==='audio'||c.kind==='video'||c.kind==='pdf'?c.kind:'binary',declaredMimeType:inspected.declaredMimeType,detectedMimeType:c.detectedMimeType,effectiveMimeType:c.effectiveMimeType,byteLength:inspected.byteLength,suggestedFilename:name,warnings:c.warnings,path},undefined,digest)}}catch{return fail('Base64 extraction failed.')}})
 ipcMain.handle('response-resources:save-as',async(_e,input)=>{const p=z.object({resourceId:id}).strict().safeParse(input);try{if(!p.success)return fail('Invalid resource.');const record=registry.getRecord(p.data.resourceId),result=await dialog.showSaveDialog({defaultPath:safeName(record.suggestedFilename)});if(result.canceled||!result.filePath)return {ok:true,data:{saved:false}};await copyFile(record.path,result.filePath);return {ok:true,data:{saved:true}}}catch{return fail('Resource could not be saved.')}})
 ipcMain.handle('response-resources:save-inline',async(_e,input)=>{const p=z.object({content:z.string().max(50*1024*1024),suggestedFilename:z.string().max(200)}).strict().safeParse(input);try{if(!p.success)return fail('Invalid inline response.');const result=await dialog.showSaveDialog({defaultPath:safeName(p.data.suggestedFilename)});if(result.canceled||!result.filePath)return {ok:true,data:{saved:false}};await writeFile(result.filePath,p.data.content);return {ok:true,data:{saved:true}}}catch{return fail('Response could not be saved.')}})
}
