import { useEffect, useState } from 'react'
type RequestDraft={id:string;name:string;protocol:'http'|'websocket'|'sse';method:string|null;url:string;description:string}
const api=()=>window.requestStudio
export default function App(){
 const [workspaces,setWorkspaces]=useState<any[]>([]),[workspace,setWorkspace]=useState(''),[collections,setCollections]=useState<any[]>([]),[requests,setRequests]=useState<RequestDraft[]>([]),[selected,setSelected]=useState<RequestDraft|null>(null),[status,setStatus]=useState('Saved'),[showEnv,setShowEnv]=useState(false)
 const load=async()=>{if(!window.requestStudio)return;const w=await api().workspaces.list();if(w.ok){setWorkspaces(w.data);setWorkspace((x)=>x||w.data[0]?.id||'')}}
 useEffect(()=>{void load()},[]); useEffect(()=>{if(!workspace)return;void Promise.all([api().collections.list(workspace),api().savedRequests.list(workspace)]).then(([c,r])=>{if(c.ok)setCollections(c.data);if(r.ok)setRequests(r.data)})},[workspace])
 const createWorkspace=async()=>{const name=prompt('Workspace name');if(name){await api().workspaces.create({name});void load()}}
 const createCollection=async()=>{const name=prompt('Collection name');if(name&&workspace){await api().collections.create({workspace_id:workspace,name});const r=await api().collections.list(workspace);if(r.ok)setCollections(r.data)}}
 const createRequest=async()=>{if(!workspace||!collections[0])return;const protocol=(prompt('Protocol: http, websocket, or sse','http')||'http') as RequestDraft['protocol'];const r=await api().savedRequests.create({workspace_id:workspace,collection_id:collections[0].id,name:'New Request',protocol,method:protocol==='http'?'GET':null,url:'',description:''});if(r.ok){setRequests([...requests,r.data]);setSelected(r.data)}}
 const update=(patch:Partial<RequestDraft>)=>{if(!selected)return;const next={...selected,...patch};if(patch.protocol)next.method=patch.protocol==='http'?'GET':null;setSelected(next);setStatus('Saving…');setTimeout(async()=>{const r=await api().savedRequests.update(next);setStatus(r.ok?'Saved':'Save failed')},350)}
 return <div className="app"><header><strong>Request Studio</strong><select aria-label="Workspace" value={workspace} onChange={e=>setWorkspace(e.target.value)}><option value="">No workspace</option>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><button onClick={createWorkspace}>New Workspace</button><span className="spacer"/><span>{status}</span><button onClick={()=>setShowEnv(!showEnv)}>Environment</button><button>Settings</button></header><div className="studio"><nav aria-label="Request explorer"><div className="pane-title">Collections <button onClick={createCollection}>+</button></div>{collections.map(c=><div key={c.id}>{c.name}</div>)}<div className="pane-title">Requests <button onClick={createRequest}>+</button></div>{requests.map(r=><button className="request" key={r.id} onClick={()=>setSelected(r)}>{r.protocol.toUpperCase()} · {r.name}</button>)}</nav><main>{selected?<><label>Name<input value={selected.name} onChange={e=>update({name:e.target.value})}/></label><div className="row"><select aria-label="Protocol" value={selected.protocol} onChange={e=>update({protocol:e.target.value as RequestDraft['protocol']})}>{['http','websocket','sse'].map(x=><option key={x}>{x}</option>)}</select>{selected.protocol==='http'&&<select aria-label="Method" value={selected.method||'GET'} onChange={e=>update({method:e.target.value})}>{['GET','POST','PUT','PATCH','DELETE'].map(x=><option key={x}>{x}</option>)}</select>}<input aria-label="URL" placeholder="Enter request URL" value={selected.url} onChange={e=>update({url:e.target.value})}/></div><label>Description<textarea value={selected.description} onChange={e=>update({description:e.target.value})}/></label></>:<div className="empty"><h2>Create or select a request</h2><p>Your request draft will appear here.</p></div>}<button disabled title="HTTP execution will be implemented in Milestone 2.">Send</button><p className="hint">HTTP execution will be implemented in Milestone 2.</p></main><aside aria-label="Response"><h2>Response</h2><div className="empty">Send a request to see the response here.</div></aside></div>{showEnv&&<div className="modal"><h2>Environments</h2><p>Environment and secret variable management is stored locally.</p><button onClick={()=>setShowEnv(false)}>Close</button></div>}</div>}
declare global { interface Window { requestStudio:any } }
