import { FormEvent, useEffect, useState } from 'react'

type Environment={id:string;name:string}
type Variable={id:string;environment_id:string;key:string;value:string;is_secret:number;description:string}
type VariableDraft={key:string;value:string;isSecret:boolean;description:string}
const emptyDraft:VariableDraft={key:'',value:'',isSecret:false,description:''}

export default function EnvironmentPanel({workspaceId,onClose,initialVariables=[]}:{workspaceId:string;onClose:()=>void;initialVariables?:Variable[]}){
 const [environments,setEnvironments]=useState<Environment[]>([]),[environmentId,setEnvironmentId]=useState(''),[variables,setVariables]=useState<Variable[]>(initialVariables),[revealed,setRevealed]=useState<Set<string>>(new Set()),[renaming,setRenaming]=useState(false),[rename,setRename]=useState(''),[editing,setEditing]=useState<Variable|null>(null),[draft,setDraft]=useState<VariableDraft>(emptyDraft),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 const loadVariables=async(id=environmentId)=>{if(!id){setVariables([]);return}const r=await window.requestStudio.variables.list(id);if(r.ok)setVariables(r.data);else setError(r.error.message)}
 const loadEnvironments=async()=>{if(!window.requestStudio||!workspaceId)return;const [list,selected]=await Promise.all([window.requestStudio.environments.list(workspaceId),window.requestStudio.environments.getSelected(workspaceId)]);if(list.ok){setEnvironments(list.data);const next=selected.ok&&selected.data&&list.data.some((e:Environment)=>e.id===selected.data)?selected.data:list.data[0]?.id||'';setEnvironmentId(next);await loadVariables(next)}}
 useEffect(()=>{setEnvironmentId('');setRevealed(new Set());void loadEnvironments()},[workspaceId])
 const choose=async(id:string)=>{setEnvironmentId(id);setRevealed(new Set());setEditing(null);await window.requestStudio.environments.select(workspaceId,id||null);await loadVariables(id)}
 const addEnvironment=async()=>{const name=prompt('Environment name')?.trim();if(!name)return;const r=await window.requestStudio.environments.create({workspace_id:workspaceId,name});if(r.ok){await loadEnvironments();await choose(r.data.id)}else setError(r.error.message)}
 const saveRename=async(e:FormEvent)=>{e.preventDefault();const name=rename.trim();if(!name){setError('Environment name is required.');return}setSaving(true);setError('');const r=await window.requestStudio.environments.rename({id:environmentId,workspaceId,name});setSaving(false);if(r.ok){setRenaming(false);await loadEnvironments()}else setError(r.error.message)}
 const removeEnvironment=async()=>{if(environmentId&&confirm('Delete this environment and all its variables?')){const r=await window.requestStudio.environments.delete({id:environmentId});if(!r.ok){setError(r.error.message);return}setEnvironmentId('');setEditing(null);await loadEnvironments()}}
 const startVariable=(variable?:Variable)=>{setError('');setEditing(variable||({id:'',environment_id:environmentId,key:'',value:'',is_secret:0,description:''}));setDraft(variable?{key:variable.key,value:variable.value,isSecret:Boolean(variable.is_secret),description:variable.description}:emptyDraft)}
 const saveVariable=async(e:FormEvent)=>{e.preventDefault();const key=draft.key.trim();if(!key){setError('Variable key is required.');return}setSaving(true);setError('');const input={environmentId,key,value:draft.value,isSecret:draft.isSecret,description:draft.description};const r=editing?.id?await window.requestStudio.variables.update({id:editing.id,...input}):await window.requestStudio.variables.create({environment_id:environmentId,key,value:draft.value,is_secret:draft.isSecret?1:0,description:draft.description});setSaving(false);if(r.ok){setEditing(null);setRevealed(new Set());await loadVariables()}else setError(r.error.message)}
 const removeVariable=async(id:string)=>{if(confirm('Delete this variable?')){const r=await window.requestStudio.variables.delete({id});if(r.ok){if(editing?.id===id)setEditing(null);await loadVariables()}else setError(r.error.message)}}
 const selected=environments.find(e=>e.id===environmentId)
 return <section className="modal" aria-label="Environment manager"><div className="pane-title"><h2>Environments</h2><button onClick={onClose}>Close</button></div>{error&&<p role="alert" className="error">{error}</p>}<div className="row"><select aria-label="Current environment" value={environmentId} onChange={e=>void choose(e.target.value)}><option value="">No environment</option>{environments.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><button onClick={addEnvironment}>New</button><button onClick={()=>{setRename(selected?.name||'');setRenaming(true);setError('')}} disabled={!environmentId}>Rename</button><button onClick={removeEnvironment} disabled={!environmentId}>Delete</button></div>{renaming&&<form className="editor" onSubmit={saveRename}><label>Environment name<input aria-label="Environment name" value={rename} maxLength={100} onChange={e=>setRename(e.target.value)} autoFocus/></label><div className="row"><button type="submit" disabled={saving}>{saving?'Saving…':'Save'}</button><button type="button" onClick={()=>setRenaming(false)} disabled={saving}>Cancel</button></div></form>}<div className="pane-title">Variables <button onClick={()=>startVariable()} disabled={!environmentId}>+</button></div>{!environmentId&&<p className="hint">Create or select an environment to manage variables.</p>}{variables.map(v=><div className="variable" key={v.id}><input aria-label={`${v.key} value`} readOnly value={v.is_secret&&!revealed.has(v.id)?'••••••••':v.value}/><span>{v.key}</span>{v.is_secret&&<button onClick={()=>setRevealed(s=>new Set(s).add(v.id))}>Reveal</button>}<button onClick={()=>startVariable(v)}>Edit</button><button onClick={()=>removeVariable(v.id)}>Delete</button></div>)}{editing&&<form className="editor" onSubmit={saveVariable}><label>Key<input aria-label="Variable key" value={draft.key} maxLength={100} onChange={e=>setDraft({...draft,key:e.target.value})}/></label><label>Value<input aria-label="Variable value" type={draft.isSecret?'password':'text'} value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})}/></label><label>Description<input aria-label="Variable description" value={draft.description} maxLength={500} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="check"><input aria-label="Secret variable" type="checkbox" checked={draft.isSecret} onChange={e=>setDraft({...draft,isSecret:e.target.checked})}/> Secret</label><div className="row"><button type="submit" disabled={saving}>{saving?'Saving…':'Save variable'}</button><button type="button" onClick={()=>setEditing(null)} disabled={saving}>Cancel</button></div></form>}<p className="hint">Secret values are masked but stored locally in plain text in Milestone 1.</p></section>
}
