import { useEffect, useState } from 'react'

type Variable={id:string;environment_id:string;key:string;value:string;is_secret:number;description:string}
export default function EnvironmentPanel({workspaceId,onClose,initialVariables=[]}:{workspaceId:string;onClose:()=>void;initialVariables?:Variable[]}){
 const [environments,setEnvironments]=useState<any[]>([]),[environmentId,setEnvironmentId]=useState(''),[variables,setVariables]=useState<Variable[]>(initialVariables),[revealed,setRevealed]=useState<Set<string>>(new Set())
 const loadEnvironments=async()=>{if(!window.requestStudio||!workspaceId)return;const r=await window.requestStudio.environments.list(workspaceId);if(r.ok){setEnvironments(r.data);setEnvironmentId((x)=>x||r.data[0]?.id||'')}}
 const loadVariables=async()=>{if(!environmentId)return;const r=await window.requestStudio.variables.list(environmentId);if(r.ok)setVariables(r.data)}
 useEffect(()=>{void loadEnvironments()},[workspaceId]);useEffect(()=>{void loadVariables()},[environmentId])
 const addEnvironment=async()=>{const name=prompt('Environment name');if(name){await window.requestStudio.environments.create({workspace_id:workspaceId,name});void loadEnvironments()}}
 const removeEnvironment=async()=>{if(environmentId&&confirm('Delete this environment and all its variables?')){await window.requestStudio.environments.delete({id:environmentId});setEnvironmentId('');void loadEnvironments()}}
 const addVariable=async()=>{if(!environmentId)return;const key=prompt('Variable key');if(key){const value=prompt('Variable value')||'';await window.requestStudio.variables.create({environment_id:environmentId,key,value,is_secret:confirm('Mark this variable as secret?')?1:0,description:''});void loadVariables()}}
 const removeVariable=async(id:string)=>{if(confirm('Delete this variable?')){await window.requestStudio.variables.delete({id});void loadVariables()}}
 return <section className="modal" aria-label="Environment manager"><div className="pane-title"><h2>Environments</h2><button onClick={onClose}>Close</button></div><div className="row"><select aria-label="Current environment" value={environmentId} onChange={e=>{setEnvironmentId(e.target.value);setRevealed(new Set())}}><option value="">No environment</option>{environments.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><button onClick={addEnvironment}>New</button><button onClick={removeEnvironment} disabled={!environmentId}>Delete</button></div><div className="pane-title">Variables <button onClick={addVariable} disabled={!environmentId}>+</button></div>{variables.map(v=><div className="variable" key={v.id}><input aria-label={`${v.key} value`} readOnly value={v.is_secret&&!revealed.has(v.id)?'••••••••':v.value}/><span>{v.key}</span>{v.is_secret&&<button onClick={()=>setRevealed(s=>new Set(s).add(v.id))}>Reveal</button>}<button onClick={()=>removeVariable(v.id)}>Delete</button></div>)}<p className="hint">Secret values are masked but stored locally in plain text in Milestone 1.</p></section>
}
