// @vitest-environment jsdom
import { fireEvent,render,screen } from '@testing-library/react'
import { beforeEach,expect,it,vi } from 'vitest'
import HttpResponsePanel from './HttpResponsePanel'
beforeEach(()=>{window.requestStudio={responseResources:{saveAs:vi.fn().mockResolvedValue({ok:true,data:{saved:true}}),readPreview:vi.fn().mockResolvedValue({ok:true,data:new Uint8Array([0x4d,0x5a,0,65])}),inspectBase64:vi.fn().mockResolvedValue({ok:true,data:{classification:{kind:'image'}}}),extractBase64:vi.fn().mockResolvedValue({ok:true,data:{id:'x',kind:'image',effectiveMimeType:'image/png',byteLength:8,suggestedFilename:'x.png',warnings:[]}})}}})
it('shows 4xx as a response and safely renders JSON',()=>{render(<HttpResponsePanel error="" response={{status:400,statusText:'Bad Request',durationMs:10,sizeBytes:7,kind:'json',headers:{'content-type':'application/json'},text:'{"x":1}'}}/>);expect(screen.getByText(/400 Bad Request/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Pretty'}));expect(screen.getByText('1')).toBeInTheDocument()})
it('selects native image, audio, video and sandboxed PDF viewers',()=>{const base={status:200,statusText:'OK',durationMs:1,sizeBytes:8,headers:{},text:null,resource:{id:'123',effectiveMimeType:'image/png',byteLength:8,suggestedFilename:'a.png',warnings:[]}};const {rerender}=render(<HttpResponsePanel error="" response={{...base,kind:'image'}}/>);fireEvent.click(screen.getByRole('button',{name:'Preview'}));expect(screen.getByRole('img')).toHaveAttribute('src','request-studio-resource://app/resource/123');rerender(<HttpResponsePanel error="" response={{...base,kind:'audio',resource:{...base.resource,effectiveMimeType:'audio/wav'}}}/>);expect(document.querySelector('audio')).toBeTruthy();rerender(<HttpResponsePanel error="" response={{...base,kind:'video',resource:{...base.resource,effectiveMimeType:'video/mp4'}}}/>);expect(document.querySelector('video')).toBeTruthy();rerender(<HttpResponsePanel error="" response={{...base,kind:'pdf',resource:{...base.resource,effectiveMimeType:'application/pdf'}}}/>);expect(screen.getByTitle('PDF preview')).toHaveAttribute('sandbox','')})
it('renders bounded binary Hex and executable warning',async()=>{render(<HttpResponsePanel error="" response={{status:200,statusText:'OK',durationMs:1,sizeBytes:4,kind:'binary',headers:{},resource:{id:'123',effectiveMimeType:'application/vnd.microsoft.portable-executable',byteLength:4,suggestedFilename:'x.exe',warnings:[]}}}/>);fireEvent.click(screen.getByRole('button',{name:'Binary'}));expect(await screen.findByText(/4d 5a 00 41/i)).toBeInTheDocument();expect(screen.getByText(/cannot be previewed safely/i)).toBeInTheDocument()})
it('offers explicit Base64 inspection only for JSON string nodes',async()=>{render(<HttpResponsePanel error="" response={{historyId:'00000000-0000-4000-8000-000000000000',status:200,statusText:'OK',durationMs:1,sizeBytes:20,kind:'json',headers:{},text:'{"audio":"UklGRg==","count":1}'}}/>);fireEvent.click(screen.getByRole('button',{name:'Pretty'}));fireEvent.click(screen.getByRole('button',{name:'Inspect $.audio as Base64'}));expect(window.requestStudio.responseResources.inspectBase64).toHaveBeenCalledWith('UklGRg==');expect(await screen.findByText(/Detected as image/)).toBeInTheDocument()})
